# Pre-commit hooks for ibi recovery toolkit
# See https://pre-commit.com for more information

repos:
  # General file quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.9
        args: [--line-length=88]

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # Python linting (disabled for initial commit due to existing code)
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
  #       args: [--max-line-length=88, --extend-ignore=E203,W503]
  #       additional_dependencies:
  #         - flake8-docstrings
  #         - flake8-bugbear
  #         - flake8-comprehensions

  # Python type checking (disabled for initial commit)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.7.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests]
  #       args: [--ignore-missing-imports]

  # Security checks (disabled for initial commit)
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       args: [-c, pyproject.toml]
  #       additional_dependencies: ["bandit[toml]"]

  # Documentation checks (disabled for now due to existing code)
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.3.0
  #   hooks:
  #     - id: pydocstyle
  #       args: [--convention=google]

  # JSON/YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [json, yaml, markdown]
        exclude: ^(poetry.lock|\.vscode/|\.github/workflows/test\.yml\.example)

  # Shell script checks
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck

  # Spell checking (disabled - repository not found)
  # - repo: https://github.com/cspell-tool/cspell
  #   rev: v8.0.0
  #   hooks:
  #     - id: cspell
  #       args: [--config=.cspell.json]
  #       files: \.(py|md|yml|yaml|json|toml)$
  #       exclude: ^(tests/|\.github/|poetry\.lock|.*\.sqlite.*|.*\.db)

# Global configuration
default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit]

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
